# Generated by Django 6.0.4 on 2026-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedPerson',
            fields=[
                ('blacklisted_id', models.AutoField(primary_key=True, serialize=False)),
                ('blacklisted_name', models.CharField(max_length=255)),
                ('case_title', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('complainant_name', models.CharField(max_length=255)),
                ('case_title', models.CharField(max_length=255)),
                ('respondent_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
